"""
COT Multi-Report Pipeline — Configuration Constants
Supports: Legacy, Disaggregated, Traders in Financial Futures
Each with Futures Only (fo) and Futures+Options Combined (co).
"""

import os
from pathlib import Path

# --- Paths ---
BASE_DIR = Path(__file__).parent
DB_PATH = BASE_DIR / "cot_data.db"
JSON_OUTPUT_DIR = BASE_DIR.parent / "frontend" / "public" / "data"

# --- Download settings ---
YEARS_TO_DOWNLOAD = 5
DOWNLOAD_TIMEOUT = 60
DOWNLOAD_RETRIES = 3
RETRY_BACKOFF = 2

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) COT-Pipeline/2.0"

# --- Lookback periods (weeks) ---
COT_INDEX_3M = 13
COT_INDEX_1Y = 52
COT_INDEX_3Y = 156
WCI_LOOKBACK = 26

# --- Statistics ---
MAX_MIN_5Y_WEEKS = 260
AVG_13W_WEEKS = 13

# --- Crowded Level thresholds ---
CROWDED_BUY_THRESHOLD = 80
CROWDED_SELL_THRESHOLD = 20

# --- Update schedule ---
DATA_STALE_DAYS = 10

# --- Price data settings ---
PRICE_YEARS = 3

# ============================================================
# Report type definitions
# ============================================================

REPORT_TYPES = ['legacy', 'disagg', 'tff']
SUBTYPES = ['fo', 'co']

REPORT_DISPLAY_NAMES = {
    'legacy': 'Legacy',
    'disagg': 'Disaggregated',
    'tff': 'Traders in Financial Futures',
}

SUBTYPE_DISPLAY_NAMES = {
    'fo': 'Futures Only',
    'co': 'Futures + Options Combined',
}

# --- URLs per report type and subtype ---
REPORT_URLS = {
    'legacy': {
        'fo': {
            'yearly': 'https://www.cftc.gov/files/dea/history/deacot{year}.zip',
            'current_week': 'https://www.cftc.gov/dea/newcot/deafut.txt',
        },
        'co': {
            'yearly': 'https://www.cftc.gov/files/dea/history/deahistfo{year}.zip',
            'current_week': 'https://www.cftc.gov/dea/newcot/deacom.txt',
        },
    },
    'disagg': {
        'fo': {
            'yearly': 'https://www.cftc.gov/files/dea/history/fut_disagg_txt_{year}.zip',
            'current_week': 'https://www.cftc.gov/dea/newcot/f_disagg.txt',
        },
        'co': {
            'yearly': 'https://www.cftc.gov/files/dea/history/com_disagg_txt_{year}.zip',
            'current_week': 'https://www.cftc.gov/dea/newcot/c_disagg.txt',
        },
    },
    'tff': {
        'fo': {
            'yearly': 'https://www.cftc.gov/files/dea/history/fut_fin_txt_{year}.zip',
            'current_week': 'https://www.cftc.gov/dea/newcot/FinFutWk.txt',
        },
        'co': {
            'yearly': 'https://www.cftc.gov/files/dea/history/com_fin_txt_{year}.zip',
            'current_week': 'https://www.cftc.gov/dea/newcot/FinComWk.txt',
        },
    },
}

# ============================================================
# Group definitions per report type
# ============================================================
# role: 'commercial' → same-direction signals
#       'speculative' → inverted signals
#       'small' → inverted signals

REPORT_GROUPS = {
    'legacy': [
        {'key': 'g1', 'name': 'Large Speculators', 'short': 'L.S', 'role': 'speculative', 'has_spread': True},
        {'key': 'g2', 'name': 'Commercials', 'short': 'Comm', 'role': 'commercial', 'has_spread': False},
        {'key': 'g3', 'name': 'Small Traders', 'short': 'ST', 'role': 'small', 'has_spread': False},
    ],
    'disagg': [
        {'key': 'g1', 'name': 'Producer/Merchant', 'short': 'PM', 'role': 'commercial', 'has_spread': False},
        {'key': 'g2', 'name': 'Swap Dealers', 'short': 'SD', 'role': 'commercial', 'has_spread': True},
        {'key': 'g3', 'name': 'Managed Money', 'short': 'MM', 'role': 'speculative', 'has_spread': True},
        {'key': 'g4', 'name': 'Other Reportables', 'short': 'OR', 'role': 'speculative', 'has_spread': True},
        {'key': 'g5', 'name': 'Non-Reportable', 'short': 'NR', 'role': 'small', 'has_spread': False},
    ],
    'tff': [
        {'key': 'g1', 'name': 'Dealer/Intermediary', 'short': 'Dealer', 'role': 'commercial', 'has_spread': True},
        {'key': 'g2', 'name': 'Asset Manager', 'short': 'AM', 'role': 'speculative', 'has_spread': True},
        {'key': 'g3', 'name': 'Leveraged Funds', 'short': 'LevFn', 'role': 'speculative', 'has_spread': True},
        {'key': 'g4', 'name': 'Other Reportables', 'short': 'OR', 'role': 'speculative', 'has_spread': True},
        {'key': 'g5', 'name': 'Non-Reportable', 'short': 'NR', 'role': 'small', 'has_spread': False},
    ],
}

# ============================================================
# Column mappings: CSV header name → internal DB column
# ============================================================

COLUMN_MAP_LEGACY = {
    'Market and Exchange Names': 'market_and_exchange',
    'As of Date in Form YYYY-MM-DD': 'report_date',
    'CFTC Contract Market Code': 'cftc_contract_code',
    'CFTC Market Code in Initials': 'exchange_code',
    'CFTC Commodity Code': 'cftc_commodity_code',
    'Open Interest (All)': 'open_interest',
    'Change in Open Interest (All)': 'oi_change',
    'Noncommercial Positions-Long (All)': 'g1_long',
    'Noncommercial Positions-Short (All)': 'g1_short',
    'Noncommercial Positions-Spreading (All)': 'g1_spread',
    'Change in Noncommercial-Long (All)': 'g1_long_change',
    'Change in Noncommercial-Short (All)': 'g1_short_change',
    'Change in Noncommercial-Spreading (All)': 'g1_spread_change',
    '% of OI-Noncommercial-Long (All)': 'g1_pct_long',
    '% of OI-Noncommercial-Short (All)': 'g1_pct_short',
    'Commercial Positions-Long (All)': 'g2_long',
    'Commercial Positions-Short (All)': 'g2_short',
    'Change in Commercial-Long (All)': 'g2_long_change',
    'Change in Commercial-Short (All)': 'g2_short_change',
    '% of OI-Commercial-Long (All)': 'g2_pct_long',
    '% of OI-Commercial-Short (All)': 'g2_pct_short',
    'Nonreportable Positions-Long (All)': 'g3_long',
    'Nonreportable Positions-Short (All)': 'g3_short',
    'Change in Nonreportable-Long (All)': 'g3_long_change',
    'Change in Nonreportable-Short (All)': 'g3_short_change',
    '% of OI-Nonreportable-Long (All)': 'g3_pct_long',
    '% of OI-Nonreportable-Short (All)': 'g3_pct_short',
    'Total Reportable Positions-Long (All)': 'total_rept_long',
    'Total Reportable Positions-Short (All)': 'total_rept_short',
}

COLUMN_MAP_DISAGG = {
    'Market_and_Exchange_Names': 'market_and_exchange',
    'Report_Date_as_YYYY-MM-DD': 'report_date',
    'CFTC_Contract_Market_Code': 'cftc_contract_code',
    'CFTC_Market_Code': 'exchange_code',
    'CFTC_Commodity_Code': 'cftc_commodity_code',
    'Open_Interest_All': 'open_interest',
    'Change_in_Open_Interest_All': 'oi_change',
    'Prod_Merc_Positions_Long_All': 'g1_long',
    'Prod_Merc_Positions_Short_All': 'g1_short',
    'Change_in_Prod_Merc_Long_All': 'g1_long_change',
    'Change_in_Prod_Merc_Short_All': 'g1_short_change',
    'Pct_of_OI_Prod_Merc_Long_All': 'g1_pct_long',
    'Pct_of_OI_Prod_Merc_Short_All': 'g1_pct_short',
    'Swap_Positions_Long_All': 'g2_long',
    'Swap__Positions_Short_All': 'g2_short',
    'Swap__Positions_Spread_All': 'g2_spread',
    'Change_in_Swap_Long_All': 'g2_long_change',
    'Change_in_Swap_Short_All': 'g2_short_change',
    'Change_in_Swap_Spread_All': 'g2_spread_change',
    'Pct_of_OI_Swap_Long_All': 'g2_pct_long',
    'Pct_of_OI_Swap_Short_All': 'g2_pct_short',
    'Pct_of_OI_Swap_Spread_All': 'g2_pct_spread',
    'M_Money_Positions_Long_All': 'g3_long',
    'M_Money_Positions_Short_All': 'g3_short',
    'M_Money_Positions_Spread_All': 'g3_spread',
    'Change_in_M_Money_Long_All': 'g3_long_change',
    'Change_in_M_Money_Short_All': 'g3_short_change',
    'Change_in_M_Money_Spread_All': 'g3_spread_change',
    'Pct_of_OI_M_Money_Long_All': 'g3_pct_long',
    'Pct_of_OI_M_Money_Short_All': 'g3_pct_short',
    'Pct_of_OI_M_Money_Spread_All': 'g3_pct_spread',
    'Other_Rept_Positions_Long_All': 'g4_long',
    'Other_Rept_Positions_Short_All': 'g4_short',
    'Other_Rept_Positions_Spread_All': 'g4_spread',
    'Change_in_Other_Rept_Long_All': 'g4_long_change',
    'Change_in_Other_Rept_Short_All': 'g4_short_change',
    'Change_in_Other_Rept_Spread_All': 'g4_spread_change',
    'Pct_of_OI_Other_Rept_Long_All': 'g4_pct_long',
    'Pct_of_OI_Other_Rept_Short_All': 'g4_pct_short',
    'Pct_of_OI_Other_Rept_Spread_All': 'g4_pct_spread',
    'NonRept_Positions_Long_All': 'g5_long',
    'NonRept_Positions_Short_All': 'g5_short',
    'Change_in_NonRept_Long_All': 'g5_long_change',
    'Change_in_NonRept_Short_All': 'g5_short_change',
    'Pct_of_OI_NonRept_Long_All': 'g5_pct_long',
    'Pct_of_OI_NonRept_Short_All': 'g5_pct_short',
    'Tot_Rept_Positions_Long_All': 'total_rept_long',
    'Tot_Rept_Positions_Short_All': 'total_rept_short',
}

COLUMN_MAP_TFF = {
    'Market_and_Exchange_Names': 'market_and_exchange',
    'Report_Date_as_YYYY-MM-DD': 'report_date',
    'CFTC_Contract_Market_Code': 'cftc_contract_code',
    'CFTC_Market_Code': 'exchange_code',
    'CFTC_Commodity_Code': 'cftc_commodity_code',
    'Open_Interest_All': 'open_interest',
    'Change_in_Open_Interest_All': 'oi_change',
    'Dealer_Positions_Long_All': 'g1_long',
    'Dealer_Positions_Short_All': 'g1_short',
    'Dealer_Positions_Spread_All': 'g1_spread',
    'Change_in_Dealer_Long_All': 'g1_long_change',
    'Change_in_Dealer_Short_All': 'g1_short_change',
    'Change_in_Dealer_Spread_All': 'g1_spread_change',
    'Pct_of_OI_Dealer_Long_All': 'g1_pct_long',
    'Pct_of_OI_Dealer_Short_All': 'g1_pct_short',
    'Pct_of_OI_Dealer_Spread_All': 'g1_pct_spread',
    'Asset_Mgr_Positions_Long_All': 'g2_long',
    'Asset_Mgr_Positions_Short_All': 'g2_short',
    'Asset_Mgr_Positions_Spread_All': 'g2_spread',
    'Change_in_Asset_Mgr_Long_All': 'g2_long_change',
    'Change_in_Asset_Mgr_Short_All': 'g2_short_change',
    'Change_in_Asset_Mgr_Spread_All': 'g2_spread_change',
    'Pct_of_OI_Asset_Mgr_Long_All': 'g2_pct_long',
    'Pct_of_OI_Asset_Mgr_Short_All': 'g2_pct_short',
    'Pct_of_OI_Asset_Mgr_Spread_All': 'g2_pct_spread',
    'Lev_Money_Positions_Long_All': 'g3_long',
    'Lev_Money_Positions_Short_All': 'g3_short',
    'Lev_Money_Positions_Spread_All': 'g3_spread',
    'Change_in_Lev_Money_Long_All': 'g3_long_change',
    'Change_in_Lev_Money_Short_All': 'g3_short_change',
    'Change_in_Lev_Money_Spread_All': 'g3_spread_change',
    'Pct_of_OI_Lev_Money_Long_All': 'g3_pct_long',
    'Pct_of_OI_Lev_Money_Short_All': 'g3_pct_short',
    'Pct_of_OI_Lev_Money_Spread_All': 'g3_pct_spread',
    'Other_Rept_Positions_Long_All': 'g4_long',
    'Other_Rept_Positions_Short_All': 'g4_short',
    'Other_Rept_Positions_Spread_All': 'g4_spread',
    'Change_in_Other_Rept_Long_All': 'g4_long_change',
    'Change_in_Other_Rept_Short_All': 'g4_short_change',
    'Change_in_Other_Rept_Spread_All': 'g4_spread_change',
    'Pct_of_OI_Other_Rept_Long_All': 'g4_pct_long',
    'Pct_of_OI_Other_Rept_Short_All': 'g4_pct_short',
    'Pct_of_OI_Other_Rept_Spread_All': 'g4_pct_spread',
    'NonRept_Positions_Long_All': 'g5_long',
    'NonRept_Positions_Short_All': 'g5_short',
    'Change_in_NonRept_Long_All': 'g5_long_change',
    'Change_in_NonRept_Short_All': 'g5_short_change',
    'Pct_of_OI_NonRept_Long_All': 'g5_pct_long',
    'Pct_of_OI_NonRept_Short_All': 'g5_pct_short',
    'Tot_Rept_Positions_Long_All': 'total_rept_long',
    'Tot_Rept_Positions_Short_All': 'total_rept_short',
}

COLUMN_MAPS = {
    'legacy': COLUMN_MAP_LEGACY,
    'disagg': COLUMN_MAP_DISAGG,
    'tff': COLUMN_MAP_TFF,
}

# ============================================================
# Full column name lists (match CSV headers exactly)
# ============================================================

COLUMN_NAMES_LEGACY = [
    "Market and Exchange Names",
    "As of Date in Form YYMMDD",
    "As of Date in Form YYYY-MM-DD",
    "CFTC Contract Market Code",
    "CFTC Market Code in Initials",
    "CFTC Region Code",
    "CFTC Commodity Code",
    "Open Interest (All)",
    "Noncommercial Positions-Long (All)",
    "Noncommercial Positions-Short (All)",
    "Noncommercial Positions-Spreading (All)",
    "Commercial Positions-Long (All)",
    "Commercial Positions-Short (All)",
    "Total Reportable Positions-Long (All)",
    "Total Reportable Positions-Short (All)",
    "Nonreportable Positions-Long (All)",
    "Nonreportable Positions-Short (All)",
    "Open Interest (Old)",
    "Noncommercial Positions-Long (Old)",
    "Noncommercial Positions-Short (Old)",
    "Noncommercial Positions-Spreading (Old)",
    "Commercial Positions-Long (Old)",
    "Commercial Positions-Short (Old)",
    "Total Reportable Positions-Long (Old)",
    "Total Reportable Positions-Short (Old)",
    "Nonreportable Positions-Long (Old)",
    "Nonreportable Positions-Short (Old)",
    "Open Interest (Other)",
    "Noncommercial Positions-Long (Other)",
    "Noncommercial Positions-Short (Other)",
    "Noncommercial Positions-Spreading (Other)",
    "Commercial Positions-Long (Other)",
    "Commercial Positions-Short (Other)",
    "Total Reportable Positions-Long (Other)",
    "Total Reportable Positions-Short (Other)",
    "Nonreportable Positions-Long (Other)",
    "Nonreportable Positions-Short (Other)",
    "Change in Open Interest (All)",
    "Change in Noncommercial-Long (All)",
    "Change in Noncommercial-Short (All)",
    "Change in Noncommercial-Spreading (All)",
    "Change in Commercial-Long (All)",
    "Change in Commercial-Short (All)",
    "Change in Total Reportable-Long (All)",
    "Change in Total Reportable-Short (All)",
    "Change in Nonreportable-Long (All)",
    "Change in Nonreportable-Short (All)",
    "% of Open Interest (OI) (All)",
    "% of OI-Noncommercial-Long (All)",
    "% of OI-Noncommercial-Short (All)",
    "% of OI-Noncommercial-Spreading (All)",
    "% of OI-Commercial-Long (All)",
    "% of OI-Commercial-Short (All)",
    "% of OI-Total Reportable-Long (All)",
    "% of OI-Total Reportable-Short (All)",
    "% of OI-Nonreportable-Long (All)",
    "% of OI-Nonreportable-Short (All)",
    "% of Open Interest (OI)(Old)",
    "% of OI-Noncommercial-Long (Old)",
    "% of OI-Noncommercial-Short (Old)",
    "% of OI-Noncommercial-Spreading (Old)",
    "% of OI-Commercial-Long (Old)",
    "% of OI-Commercial-Short (Old)",
    "% of OI-Total Reportable-Long (Old)",
    "% of OI-Total Reportable-Short (Old)",
    "% of OI-Nonreportable-Long (Old)",
    "% of OI-Nonreportable-Short (Old)",
    "% of Open Interest (OI) (Other)",
    "% of OI-Noncommercial-Long (Other)",
    "% of OI-Noncommercial-Short (Other)",
    "% of OI-Noncommercial-Spreading (Other)",
    "% of OI-Commercial-Long (Other)",
    "% of OI-Commercial-Short (Other)",
    "% of OI-Total Reportable-Long (Other)",
    "% of OI-Total Reportable-Short (Other)",
    "% of OI-Nonreportable-Long (Other)",
    "% of OI-Nonreportable-Short (Other)",
    "Traders-Total (All)",
    "Traders-Noncommercial-Long (All)",
    "Traders-Noncommercial-Short (All)",
    "Traders-Noncommercial-Spreading (All)",
    "Traders-Commercial-Long (All)",
    "Traders-Commercial-Short (All)",
    "Traders-Total Reportable-Long (All)",
    "Traders-Total Reportable-Short (All)",
    "Traders-Total (Old)",
    "Traders-Noncommercial-Long (Old)",
    "Traders-Noncommercial-Short (Old)",
    "Traders-Noncommercial-Spreading (Old)",
    "Traders-Commercial-Long (Old)",
    "Traders-Commercial-Short (Old)",
    "Traders-Total Reportable-Long (Old)",
    "Traders-Total Reportable-Short (Old)",
    "Traders-Total (Other)",
    "Traders-Noncommercial-Long (Other)",
    "Traders-Noncommercial-Short (Other)",
    "Traders-Noncommercial-Spreading (Other)",
    "Traders-Commercial-Long (Other)",
    "Traders-Commercial-Short (Other)",
    "Traders-Total Reportable-Long (Other)",
    "Traders-Total Reportable-Short (Other)",
    "Concentration-Gross LT 4 TDR-Long (All)",
    "Concentration-Gross LT 4 TDR-Short (All)",
    "Concentration-Gross LT 8 TDR-Long (All)",
    "Concentration-Gross LT 8 TDR-Short (All)",
    "Concentration-Net LT 4 TDR-Long (All)",
    "Concentration-Net LT 4 TDR-Short (All)",
    "Concentration-Net LT 8 TDR-Long (All)",
    "Concentration-Net LT 8 TDR-Short (All)",
    "Concentration-Gross LT 4 TDR-Long (Old)",
    "Concentration-Gross LT 4 TDR-Short (Old)",
    "Concentration-Gross LT 8 TDR-Long (Old)",
    "Concentration-Gross LT 8 TDR-Short (Old)",
    "Concentration-Net LT 4 TDR-Long (Old)",
    "Concentration-Net LT 4 TDR-Short (Old)",
    "Concentration-Net LT 8 TDR-Long (Old)",
    "Concentration-Net LT 8 TDR-Short (Old)",
    "Concentration-Gross LT 4 TDR-Long (Other)",
    "Concentration-Gross LT 4 TDR-Short(Other)",
    "Concentration-Gross LT 8 TDR-Long (Other)",
    "Concentration-Gross LT 8 TDR-Short(Other)",
    "Concentration-Net LT 4 TDR-Long (Other)",
    "Concentration-Net LT 4 TDR-Short (Other)",
    "Concentration-Net LT 8 TDR-Long (Other)",
    "Concentration-Net LT 8 TDR-Short (Other)",
    "Contract Units",
    "CFTC Contract Market Code (Quotes)",
    "CFTC Market Code in Initials (Quotes)",
    "CFTC Commodity Code (Quotes)",
]

COLUMN_NAMES_DISAGG = [
    "Market_and_Exchange_Names",
    "As_of_Date_In_Form_YYMMDD",
    "Report_Date_as_YYYY-MM-DD",
    "CFTC_Contract_Market_Code",
    "CFTC_Market_Code",
    "CFTC_Region_Code",
    "CFTC_Commodity_Code",
    "Open_Interest_All",
    "Prod_Merc_Positions_Long_All",
    "Prod_Merc_Positions_Short_All",
    "Swap_Positions_Long_All",
    "Swap__Positions_Short_All",
    "Swap__Positions_Spread_All",
    "M_Money_Positions_Long_All",
    "M_Money_Positions_Short_All",
    "M_Money_Positions_Spread_All",
    "Other_Rept_Positions_Long_All",
    "Other_Rept_Positions_Short_All",
    "Other_Rept_Positions_Spread_All",
    "Tot_Rept_Positions_Long_All",
    "Tot_Rept_Positions_Short_All",
    "NonRept_Positions_Long_All",
    "NonRept_Positions_Short_All",
    "Open_Interest_Old",
    "Prod_Merc_Positions_Long_Old",
    "Prod_Merc_Positions_Short_Old",
    "Swap_Positions_Long_Old",
    "Swap__Positions_Short_Old",
    "Swap__Positions_Spread_Old",
    "M_Money_Positions_Long_Old",
    "M_Money_Positions_Short_Old",
    "M_Money_Positions_Spread_Old",
    "Other_Rept_Positions_Long_Old",
    "Other_Rept_Positions_Short_Old",
    "Other_Rept_Positions_Spread_Old",
    "Tot_Rept_Positions_Long_Old",
    "Tot_Rept_Positions_Short_Old",
    "NonRept_Positions_Long_Old",
    "NonRept_Positions_Short_Old",
    "Open_Interest_Other",
    "Prod_Merc_Positions_Long_Other",
    "Prod_Merc_Positions_Short_Other",
    "Swap_Positions_Long_Other",
    "Swap__Positions_Short_Other",
    "Swap__Positions_Spread_Other",
    "M_Money_Positions_Long_Other",
    "M_Money_Positions_Short_Other",
    "M_Money_Positions_Spread_Other",
    "Other_Rept_Positions_Long_Other",
    "Other_Rept_Positions_Short_Other",
    "Other_Rept_Positions_Spread_Other",
    "Tot_Rept_Positions_Long_Other",
    "Tot_Rept_Positions_Short_Other",
    "NonRept_Positions_Long_Other",
    "NonRept_Positions_Short_Other",
    "Change_in_Open_Interest_All",
    "Change_in_Prod_Merc_Long_All",
    "Change_in_Prod_Merc_Short_All",
    "Change_in_Swap_Long_All",
    "Change_in_Swap_Short_All",
    "Change_in_Swap_Spread_All",
    "Change_in_M_Money_Long_All",
    "Change_in_M_Money_Short_All",
    "Change_in_M_Money_Spread_All",
    "Change_in_Other_Rept_Long_All",
    "Change_in_Other_Rept_Short_All",
    "Change_in_Other_Rept_Spread_All",
    "Change_in_Tot_Rept_Long_All",
    "Change_in_Tot_Rept_Short_All",
    "Change_in_NonRept_Long_All",
    "Change_in_NonRept_Short_All",
    "Pct_of_Open_Interest_All",
    "Pct_of_OI_Prod_Merc_Long_All",
    "Pct_of_OI_Prod_Merc_Short_All",
    "Pct_of_OI_Swap_Long_All",
    "Pct_of_OI_Swap_Short_All",
    "Pct_of_OI_Swap_Spread_All",
    "Pct_of_OI_M_Money_Long_All",
    "Pct_of_OI_M_Money_Short_All",
    "Pct_of_OI_M_Money_Spread_All",
    "Pct_of_OI_Other_Rept_Long_All",
    "Pct_of_OI_Other_Rept_Short_All",
    "Pct_of_OI_Other_Rept_Spread_All",
    "Pct_of_OI_Tot_Rept_Long_All",
    "Pct_of_OI_Tot_Rept_Short_All",
    "Pct_of_OI_NonRept_Long_All",
    "Pct_of_OI_NonRept_Short_All",
    "Pct_of_Open_Interest_Old",
    "Pct_of_OI_Prod_Merc_Long_Old",
    "Pct_of_OI_Prod_Merc_Short_Old",
    "Pct_of_OI_Swap_Long_Old",
    "Pct_of_OI_Swap_Short_Old",
    "Pct_of_OI_Swap_Spread_Old",
    "Pct_of_OI_M_Money_Long_Old",
    "Pct_of_OI_M_Money_Short_Old",
    "Pct_of_OI_M_Money_Spread_Old",
    "Pct_of_OI_Other_Rept_Long_Old",
    "Pct_of_OI_Other_Rept_Short_Old",
    "Pct_of_OI_Other_Rept_Spread_Old",
    "Pct_of_OI_Tot_Rept_Long_Old",
    "Pct_of_OI_Tot_Rept_Short_Old",
    "Pct_of_OI_NonRept_Long_Old",
    "Pct_of_OI_NonRept_Short_Old",
    "Pct_of_Open_Interest_Other",
    "Pct_of_OI_Prod_Merc_Long_Other",
    "Pct_of_OI_Prod_Merc_Short_Other",
    "Pct_of_OI_Swap_Long_Other",
    "Pct_of_OI_Swap_Short_Other",
    "Pct_of_OI_Swap_Spread_Other",
    "Pct_of_OI_M_Money_Long_Other",
    "Pct_of_OI_M_Money_Short_Other",
    "Pct_of_OI_M_Money_Spread_Other",
    "Pct_of_OI_Other_Rept_Long_Other",
    "Pct_of_OI_Other_Rept_Short_Other",
    "Pct_of_OI_Other_Rept_Spread_Other",
    "Pct_of_OI_Tot_Rept_Long_Other",
    "Pct_of_OI_Tot_Rept_Short_Other",
    "Pct_of_OI_NonRept_Long_Other",
    "Pct_of_OI_NonRept_Short_Other",
    "Traders_Tot_All",
    "Traders_Prod_Merc_Long_All",
    "Traders_Prod_Merc_Short_All",
    "Traders_Swap_Long_All",
    "Traders_Swap_Short_All",
    "Traders_Swap_Spread_All",
    "Traders_M_Money_Long_All",
    "Traders_M_Money_Short_All",
    "Traders_M_Money_Spread_All",
    "Traders_Other_Rept_Long_All",
    "Traders_Other_Rept_Short_All",
    "Traders_Other_Rept_Spread_All",
    "Traders_Tot_Rept_Long_All",
    "Traders_Tot_Rept_Short_All",
    "Traders_Tot_Old",
    "Traders_Prod_Merc_Long_Old",
    "Traders_Prod_Merc_Short_Old",
    "Traders_Swap_Long_Old",
    "Traders_Swap_Short_Old",
    "Traders_Swap_Spread_Old",
    "Traders_M_Money_Long_Old",
    "Traders_M_Money_Short_Old",
    "Traders_M_Money_Spread_Old",
    "Traders_Other_Rept_Long_Old",
    "Traders_Other_Rept_Short_Old",
    "Traders_Other_Rept_Spread_Old",
    "Traders_Tot_Rept_Long_Old",
    "Traders_Tot_Rept_Short_Old",
    "Traders_Tot_Other",
    "Traders_Prod_Merc_Long_Other",
    "Traders_Prod_Merc_Short_Other",
    "Traders_Swap_Long_Other",
    "Traders_Swap_Short_Other",
    "Traders_Swap_Spread_Other",
    "Traders_M_Money_Long_Other",
    "Traders_M_Money_Short_Other",
    "Traders_M_Money_Spread_Other",
    "Traders_Other_Rept_Long_Other",
    "Traders_Other_Rept_Short_Other",
    "Traders_Other_Rept_Spread_Other",
    "Traders_Tot_Rept_Long_Other",
    "Traders_Tot_Rept_Short_Other",
    "Conc_Gross_LE_4_TDR_Long_All",
    "Conc_Gross_LE_4_TDR_Short_All",
    "Conc_Gross_LE_8_TDR_Long_All",
    "Conc_Gross_LE_8_TDR_Short_All",
    "Conc_Net_LE_4_TDR_Long_All",
    "Conc_Net_LE_4_TDR_Short_All",
    "Conc_Net_LE_8_TDR_Long_All",
    "Conc_Net_LE_8_TDR_Short_All",
    "Conc_Gross_LE_4_TDR_Long_Old",
    "Conc_Gross_LE_4_TDR_Short_Old",
    "Conc_Gross_LE_8_TDR_Long_Old",
    "Conc_Gross_LE_8_TDR_Short_Old",
    "Conc_Net_LE_4_TDR_Long_Old",
    "Conc_Net_LE_4_TDR_Short_Old",
    "Conc_Net_LE_8_TDR_Long_Old",
    "Conc_Net_LE_8_TDR_Short_Old",
    "Conc_Gross_LE_4_TDR_Long_Other",
    "Conc_Gross_LE_4_TDR_Short_Other",
    "Conc_Gross_LE_8_TDR_Long_Other",
    "Conc_Gross_LE_8_TDR_Short_Other",
    "Conc_Net_LE_4_TDR_Long_Other",
    "Conc_Net_LE_4_TDR_Short_Other",
    "Conc_Net_LE_8_TDR_Long_Other",
    "Conc_Net_LE_8_TDR_Short_Other",
    "Contract_Units",
    "CFTC_Contract_Market_Code_Quotes",
    "CFTC_Market_Code_Quotes",
    "CFTC_Commodity_Code_Quotes",
    "CFTC_SubGroup_Code",
    "FutOnly_or_Combined",
]

COLUMN_NAMES_TFF = [
    "Market_and_Exchange_Names",
    "As_of_Date_In_Form_YYMMDD",
    "Report_Date_as_YYYY-MM-DD",
    "CFTC_Contract_Market_Code",
    "CFTC_Market_Code",
    "CFTC_Region_Code",
    "CFTC_Commodity_Code",
    "Open_Interest_All",
    "Dealer_Positions_Long_All",
    "Dealer_Positions_Short_All",
    "Dealer_Positions_Spread_All",
    "Asset_Mgr_Positions_Long_All",
    "Asset_Mgr_Positions_Short_All",
    "Asset_Mgr_Positions_Spread_All",
    "Lev_Money_Positions_Long_All",
    "Lev_Money_Positions_Short_All",
    "Lev_Money_Positions_Spread_All",
    "Other_Rept_Positions_Long_All",
    "Other_Rept_Positions_Short_All",
    "Other_Rept_Positions_Spread_All",
    "Tot_Rept_Positions_Long_All",
    "Tot_Rept_Positions_Short_All",
    "NonRept_Positions_Long_All",
    "NonRept_Positions_Short_All",
    "Change_in_Open_Interest_All",
    "Change_in_Dealer_Long_All",
    "Change_in_Dealer_Short_All",
    "Change_in_Dealer_Spread_All",
    "Change_in_Asset_Mgr_Long_All",
    "Change_in_Asset_Mgr_Short_All",
    "Change_in_Asset_Mgr_Spread_All",
    "Change_in_Lev_Money_Long_All",
    "Change_in_Lev_Money_Short_All",
    "Change_in_Lev_Money_Spread_All",
    "Change_in_Other_Rept_Long_All",
    "Change_in_Other_Rept_Short_All",
    "Change_in_Other_Rept_Spread_All",
    "Change_in_Tot_Rept_Long_All",
    "Change_in_Tot_Rept_Short_All",
    "Change_in_NonRept_Long_All",
    "Change_in_NonRept_Short_All",
    "Pct_of_Open_Interest_All",
    "Pct_of_OI_Dealer_Long_All",
    "Pct_of_OI_Dealer_Short_All",
    "Pct_of_OI_Dealer_Spread_All",
    "Pct_of_OI_Asset_Mgr_Long_All",
    "Pct_of_OI_Asset_Mgr_Short_All",
    "Pct_of_OI_Asset_Mgr_Spread_All",
    "Pct_of_OI_Lev_Money_Long_All",
    "Pct_of_OI_Lev_Money_Short_All",
    "Pct_of_OI_Lev_Money_Spread_All",
    "Pct_of_OI_Other_Rept_Long_All",
    "Pct_of_OI_Other_Rept_Short_All",
    "Pct_of_OI_Other_Rept_Spread_All",
    "Pct_of_OI_Tot_Rept_Long_All",
    "Pct_of_OI_Tot_Rept_Short_All",
    "Pct_of_OI_NonRept_Long_All",
    "Pct_of_OI_NonRept_Short_All",
    "Traders_Tot_All",
    "Traders_Dealer_Long_All",
    "Traders_Dealer_Short_All",
    "Traders_Dealer_Spread_All",
    "Traders_Asset_Mgr_Long_All",
    "Traders_Asset_Mgr_Short_All",
    "Traders_Asset_Mgr_Spread_All",
    "Traders_Lev_Money_Long_All",
    "Traders_Lev_Money_Short_All",
    "Traders_Lev_Money_Spread_All",
    "Traders_Other_Rept_Long_All",
    "Traders_Other_Rept_Short_All",
    "Traders_Other_Rept_Spread_All",
    "Traders_Tot_Rept_Long_All",
    "Traders_Tot_Rept_Short_All",
    "Conc_Gross_LE_4_TDR_Long_All",
    "Conc_Gross_LE_4_TDR_Short_All",
    "Conc_Gross_LE_8_TDR_Long_All",
    "Conc_Gross_LE_8_TDR_Short_All",
    "Conc_Net_LE_4_TDR_Long_All",
    "Conc_Net_LE_4_TDR_Short_All",
    "Conc_Net_LE_8_TDR_Long_All",
    "Conc_Net_LE_8_TDR_Short_All",
    "Contract_Units",
    "CFTC_Contract_Market_Code_Quotes",
    "CFTC_Market_Code_Quotes",
    "CFTC_Commodity_Code_Quotes",
    "CFTC_SubGroup_Code",
    "FutOnly_or_Combined",
]

COLUMN_NAMES_MAP = {
    'legacy': COLUMN_NAMES_LEGACY,
    'disagg': COLUMN_NAMES_DISAGG,
    'tff': COLUMN_NAMES_TFF,
}

DATE_COLUMN_MAP = {
    'legacy': 'As of Date in Form YYYY-MM-DD',
    'disagg': 'Report_Date_as_YYYY-MM-DD',
    'tff': 'Report_Date_as_YYYY-MM-DD',
}

MARKET_CATEGORIES = {
    'currencies': {
        'keywords': ['USD INDEX', 'EURO FX', 'BRITISH POUND', 'JAPANESE YEN',
                     'SWISS FRANC', 'CANADIAN DOLLAR', 'AUSTRALIAN DOLLAR',
                     'NEW ZEALAND DOLLAR', 'MEXICAN PESO', 'BRAZILIAN REAL',
                     'RUSSIAN RUBLE', 'S. AFRICAN RAND'],
        'display': 'Currencies'
    },
    'crypto': {
        'keywords': ['BITCOIN', 'MICRO BITCOIN', 'ETHER', 'NANO BITCOIN', 'NANO ETHER',
                     'SHIB', 'SOLANA', 'XRP', 'DOGECOIN'],
        'display': 'Crypto'
    },
    'metals': {
        'keywords': ['GOLD', 'SILVER', 'COPPER', 'PLATINUM', 'PALLADIUM', 'ALUMINUM'],
        'display': 'Metals'
    },
    'energy': {
        'keywords': ['CRUDE OIL', 'NATURAL GAS', 'HEATING OIL', 'RBOB GASOLINE',
                     'BRENT CRUDE'],
        'display': 'Energy'
    },
    'grains': {
        'keywords': ['WHEAT', 'CORN', 'SOYBEANS', 'SOYBEAN OIL', 'SOYBEAN MEAL',
                     'OATS', 'ROUGH RICE'],
        'display': 'Grains'
    },
    'softs': {
        'keywords': ['COFFEE', 'COCOA', 'SUGAR', 'COTTON', 'ORANGE JUICE', 'LUMBER'],
        'display': 'Softs'
    },
    'livestock': {
        'keywords': ['LIVE CATTLE', 'FEEDER CATTLE', 'LEAN HOGS'],
        'display': 'Livestock'
    },
    'indices': {
        'keywords': ['S&P 500', 'E-MINI S&P', 'NASDAQ', 'DOW JONES', 'RUSSELL',
                     'VIX', 'NIKKEI'],
        'display': 'Indices'
    },
    'rates': {
        'keywords': ['2-YEAR', '5-YEAR', '10-YEAR', '30-YEAR', 'EURODOLLAR',
                     'FED FUNDS', 'TREASURY', 'T-NOTE', 'T-BOND', 'ULTRA'],
        'display': 'Rates'
    },
}

TICKER_MAP = {
    '133741': 'BTC-USD', '133742': 'BTC-USD', '146021': 'ETH-USD',
    '146022': 'ETH-USD', '176740': 'XRP-USD', '177741': 'SOL-USD',
    '099741': '6E=F', '096742': '6B=F', '097741': '6J=F',
    '090741': '6C=F', '232741': '6A=F', '112741': '6N=F',
    '092741': '6S=F', '098662': 'DX=F', '095741': '6M=F', '102741': '6L=F',
    '067411': 'CL=F', '023651': 'NG=F', '022651': 'HO=F',
    '111416': 'RB=F', '06765T': 'BZ=F', '067651': 'CL=F',
    '001602': 'ZW=F', '001612': 'KE=F', '002602': 'ZC=F',
    '005602': 'ZS=F', '005603': 'ZS=F', '026603': 'ZM=F',
    '007601': 'ZL=F', '004603': 'ZO=F', '039601': 'ZR=F',
    '088691': 'GC=F', '088695': 'GC=F', '084691': 'SI=F',
    '084694': 'SI=F', '085692': 'HG=F', '085699': 'HG=F',
    '076651': 'PL=F', '075651': 'PA=F',
    '13874A': 'ES=F', '13874+': 'ES=F', '13874U': 'ES=F',
    '209742': 'NQ=F', '20974+': 'NQ=F', '209747': 'NQ=F',
    '239742': 'RTY=F', '239747': 'RTY=F',
    '124603': 'YM=F', '12460+': 'YM=F', '240741': 'NKD=F', '1170E1': '^VIX',
    '057642': 'LE=F', '061641': 'GF=F', '054642': 'HE=F',
    '073732': 'CC=F', '083731': 'KC=F', '033661': 'CT=F',
    '080732': 'SB=F', '040701': 'OJ=F', '058644': 'LBS=F',
    '043602': 'ZN=F', '042601': 'ZT=F', '044601': 'ZF=F',
    '020601': 'ZB=F', '043607': 'TN=F', '020604': 'UB=F',
}
